p1r1:
  hostname: "p1r1"
  groups:
    - "router"
    - "pod1"
p1r2:
  hostname: "p1r2"
  groups:
    - "router"
    - "pod1"
p1r3:
  hostname: "p1r3"
  groups:
    - "router"
    - "pod1"
p1r4:
  hostname: "p1r4"
  groups:
    - "router"
    - "pod1"
p1r5:
  hostname: "p1r5"
  groups:
    - "router"
    - "pod1"
p1r6:
  hostname: "p1r6"
  groups:
    - "router"
p1r7:
  hostname: "p1r7"
  groups:
    - "router"
    - "pod1"
p1r8:
  hostname: "p1r8"
  groups:
    - "router"
    - "pod1"

p1sw11:
  hostname: "p1sw11"
  groups:
    - "switch"
    - "pod1"
p2sw12:
  hostname: "p2sw12"
  groups:
    - "switch"
    - "pod2"
p2sw13:
  hostname: "p2sw13"
  groups:
    - "switch"
    - "pod3"
p2sw14:
  hostname: "p2sw14"
  groups:
    - "switch"
    - "pod4"
